### ISSUE TITLE
Using the 'Copy to Clipboard' and 'Paste from Clipboard' functions it is possible to have multiple Mod Blocks with no way of removing them

### ISSUE THREAD

**Issue by xuvvy** [LennardF1989/BF2042-Portal-Extensions#1]
As the title says, the extension allows the user to copy and paste the Mod block, which is the main block that determines what code is being run and there is no way of removing said mod block after pasting it, since it's not meant to ever be any other mod block other than the single default one.

Not sure what the implication is of having two or more mod blocks is, but we should at least have a way of removing it after pasting it.

**Comment by LennardF1989** [comment]
Yep, I'll have to figure out something for that.

**Comment by xuvvy** [comment]
Running a command `_Blockly.selected.dispose(false)` in the browser Console will remove selected Block, including Mod block. Perhaps you can implement this feature when right clicking a Mod block?

Alternatively, you can make it so that it automatically removes a Mod block on paste, since there should never, ever be two Mod blocks and Mod blocks cannot be removed normally anyway.

It is useful to make copies with Mod blocks as it can contain multiple Rules which can then be copied as a single XML prefab, so that's why we need an optimal solution to deal with inevitable extra Mod blocks.

**Comment by LennardF1989** [comment]
Fixed, I added an option to delete a mod block if more than one is available.
