### ISSUE TITLE
Feature request: Extension Name Change

### ISSUE THREAD

**Issue by xuvvy** [LennardF1989/BF2042-Portal-Extensions#10]
Now is the time to consider a name change before both Portal and this extension become significantly more popular. It is odd to say "BF2042 Portal Extensions extension" and I assume that discoverability will be very low with such a name, so I think a name change to something either more distinguishable or more in line with other extensions that serve a similar purpose for other websites would be a good idea.

**Here's some possible names:**
* Battlefield Portal Enhanced
* Enhanced Portal
* Augmented Portal
* Better Portal
* Portal Editor
* Portal Rules Editor Plus
* Portal Rules Editor Enhancement Suite
* Battlefield Portal Enhancement Suite
* Portal Rules Editor Improved

**Comment by LennardF1989** [comment]
As it's an established name by now, this is not going to happen anymore.
