### ISSUE TITLE
Feature Request : Add a options to export a block(s) as a image

### ISSUE THREAD

**Issue by p0lygun** [LennardF1989/BF2042-Portal-Extensions#11]
Feature Request : Add a options to export a block(s) as a image
things to do 

- [ ] select image forma to export
- [ ] select default exporting location (clipboard or disk)

as more as more features are being added to the extension i think having a second context menu inside the main context menu would keep things clean

**Comment by LennardF1989** [comment]
With the "Add Blocks" feature added, I now have sub-contextmenus, so restructuring was already on my list :) Nice request, thanks!

**Comment by LennardF1989** [comment]
This will be available in v1.0.6 :)
