### ISSUE TITLE
Plugins never load on page other than `/experience/rules`

### ISSUE THREAD

**Issue by p0lygun** [LennardF1989/BF2042-Portal-Extensions#22]
this happens because this plugins is checking for available `blocks`

https://github.com/LennardF1989/BF2042-Portal-Extensions/blob/ba58467e605dc9ea29a2bfd348d5dd790767bc43/src/web/app.js#L962-L966

**Comment by LennardF1989** [comment]
There is no use in loading plugins if there is no Blockly, and Blockly is only loaded/started once you get into the Rules Editor.

What are you trying to do/achieve?

**Comment by LennardF1989** [comment]
I see what you mean now - seems like they changed a few things and the Rules Editor is not actually supposed to be available when you haven't created your experience yet. There are some ways around the restriction, but things will go wrong regardless.

I've restructured this whole setup now, which should load plugins properly whenever the workspace changes.
