### ISSUE TITLE
Feature Request: Copy/paste A selection of blocks

### ISSUE THREAD

**Issue by leona** [LennardF1989/BF2042-Portal-Extensions#4]
Would be really great to have this feature. Copying over large amounts of changes from a staging project can be really tedious.

**Comment by LennardF1989** [comment]
Copy/paste all blocks will be available in v1.0.5, also see #9 - I will add some for of multiple selection.

**Comment by leona** [comment]
Great, thanks a million. I've updated the title so as to avoid being a duplicate.

**Comment by LennardF1989** [comment]
This will be available in v1.0.6 :)
