### ISSUE TITLE
Feature Request: Add option to show and insert snippets

### ISSUE THREAD

**Issue by LennardF1989** [LennardF1989/BF2042-Portal-Extensions#7]
As a user, I want to be able to insert all snippets that people have added to [associated repositories](https://github.com/Andygmb/Battlefield-Portal-Blocks), so I don't have to manually copy/paste code.

**Comment by LennardF1989** [comment]
Also includes the possibility to maintain your own private snippet library for easy re-use.

**Comment by The0zzy** [comment]
https://github.com/The0zzy/bf2042-portal-snippet-plugin

**Comment by LennardF1989** [comment]
This is awesome @The0zzy - Added it to the curated list in the next update :)
