### ISSUE TITLE
Feature request: Copy and paste the entire Workspace (Subroutines included) as an XML/TXT file

### ISSUE THREAD

**Issue by xuvvy** [LennardF1989/BF2042-Portal-Extensions#9]
Currently, we are limited to being able to copy-paste only one Block at a time, and while the band aid solution to that is to copy the entire Mod block, it is not possible to properly copy or paste Subroutines along side the rest of the Blocks.

It would be great if we were able to, when right-clicking on an empty surface and the Mod block, have an option to 'Copy Entire Workspace'.

**Comment by LennardF1989** [comment]
I've got a working piece of code for this - will implement this as part of the extension somewhere tonight.

**Comment by LennardF1989** [comment]
This will be in v1.0.5! The format is JSON and contains the full workspace, including variables and subroutines.
